Arqsi/Lugares_Cancela_Visita/ARQSI_Projeto/Visita/Controllers/POIsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DataAccessLibrary.Models;
using NewVisita.Models;
using NewVisita.Helpers;
using Newtonsoft.Json;
using System.Net.Http;

namespace Visita.Controllers
{
    [LoggedIn]
    public class POIsController : Controller
    {

        string url = "api/POIs/";

        // GET: Meteorologies
        public async Task<ActionResult> Index()
        {
            var client = WebApiHttpClient.GetClient();
            HttpResponseMessage response = await client.GetAsync(url);
            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var pois =
                JsonConvert.DeserializeObject<IEnumerable<POI>>(content);

                return View(pois);
            }
            else
            {
                return Content("An error has occurred: " + response.StatusCode);
            }
        }


    }
}

Arqsi/Lugares_Cancela_Visita/ARQSI_Projeto/Visita/Controllers/QuerysController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DataAccessLibrary.Models;
using NewVisita.Models;
using NewVisita.Helpers;
using Newtonsoft.Json;
using System.Net.Http;

namespace Visita.Controllers
{
    [LoggedIn]
    public class QuerysController : Controller
    {
        public ActionResult POI([Bind(Include = "POIID,Name,Description,LocalID,Local")] DataHelper data)
        {
            if (data == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View(data);
        }

        [HttpPost]
        public ActionResult GetResults([Bind(Include = "Name,Description,Local,LocalID, TimeOfReadingMin, TimeOfReadingMax, HourOfReadingMin, HourOfReadingMax, Description")] DataHelper data)
        {
            if (ModelState.IsValid)
            {
                IEnumerable<Meteorology> meteos = data.ValidMeteorologies();
                if (meteos == null)
                {
                    return View("~/Views/Querys/NotFound.cshtml");
                }
                return View(meteos);
            }
            return View("POI", data);
        }

    }
}

Arqsi/Lugares_Cancela_Visita/ARQSI_Projeto/Visita/Views/Querys/GetResults.cshtml
@model IEnumerable<DataAccessLibrary.Models.Meteorology>

@{
    ViewBag.Title = "Results";
}

<h2>Results:</h2>

<table class="table">
    <tr>
        <th>
            Local
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TimeOfReading)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HourOfReading)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Temperature)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Wind)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Humidity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pressure)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NO)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NO2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CO2)
        </th>
        <th></th>
    </tr>
    @{
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Local.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TimeOfReading)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HourOfReading)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Temperature)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Wind)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Humidity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Pressure)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NO)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NO2)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CO2)
                </td>
            </tr>
        }
    }
</table>

Arqsi/Lugares_Cancela_Visita/ARQSI_Projeto/Visita/Views/Querys/NotFound.cshtml
@model System.Web.Mvc.HandleErrorInfo

@{
    ViewBag.Title = "Error";
}

<h1 class="text-danger">Error.</h1>
<h2 class="text-danger">There was no meteorology data for the selected filters, please try again.</h2>

Arqsi/Lugares_Cancela_Visita/ARQSI_Projeto/Visita/Views/Querys/POI.cshtml
@model NewVisita.Models.DataHelper
@{
    ViewBag.Title = "Additional";
}

<h2>Complete with Additional information:</h2>

<h3>Selected POI:</h3>
<div class="col-md-offset-1">
    <b>
        @Html.DisplayNameFor(model => model.Local):
    </b>
    @Html.DisplayFor(model => model.Local)
    <br />
    <b>
        @Html.DisplayNameFor(model => model.Name):
    </b>
    @Html.DisplayFor(model => model.Name)
    <br />
    <b>
        @Html.DisplayNameFor(model => model.Description):
    </b>
    @Html.DisplayFor(model => model.Description)
</div>

<br />
<h3>Specify date and time range:</h3>
@using (Html.BeginForm("GetResults", "Querys", new { LocalID = Model.LocalID, Name = Model.Name, Description = Model.Description, Local = Model.Local }))
{
    <div class="col-md-offset-1">
        <div class="form-horizontal">
            <div class="form-group">
                <h5>Time of Reading:</h5>
                <div class="col-md-offset-1">
                    Min:  @Html.TextBoxFor(model => model.TimeOfReadingMin, new { type = "date" })
                    @Html.ValidationMessageFor(model => model.TimeOfReadingMin, "", new { @class = "text-danger" })
                    <br />
                    Max: @Html.TextBoxFor(model => model.TimeOfReadingMax, new { type = "date" })
                    @Html.ValidationMessageFor(model => model.TimeOfReadingMax, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <h5>Hour of Reading:</h5>
                <div class="col-md-offset-1">
                    Min:  @Html.TextBoxFor(model => model.HourOfReadingMin, new { type = "time" })
                    @Html.ValidationMessageFor(model => model.HourOfReadingMin, "", new { @class = "text-danger" })
                    <br />
                    Max: @Html.TextBoxFor(model => model.HourOfReadingMax, new { type = "time" })
                    @Html.ValidationMessageFor(model => model.HourOfReadingMax, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-md-offset-1">
                <input type="submit" value="Submit" />
            </div>
        </div>
    </div>
}